/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author AARSHEYA
 */
public class PageMain extends javax.swing.JFrame {

    public PageMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        services = new javax.swing.JMenu();
        travelPlan = new javax.swing.JMenuItem();
        cancel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        print = new javax.swing.JMenuItem();
        CheckPNR = new javax.swing.JMenuItem();
        passengerList = new javax.swing.JMenuItem();
        Profile = new javax.swing.JMenu();
        profile = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        trainSchedule = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenu();
        exitApp = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Page");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aa.jpg"))); // NOI18N

        services.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        services.setText("Services");

        travelPlan.setFont(new java.awt.Font("Tahoma", 1, 12));
        travelPlan.setText("Plan my Travel ");
        travelPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travelPlanActionPerformed(evt);
            }
        });
        services.add(travelPlan);

        cancel.setFont(new java.awt.Font("Tahoma", 1, 12));
        cancel.setText("Cancel e-Ticket");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        services.add(cancel);

        jMenuBar1.add(services);

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jMenu2.setText("Enquiry");

        print.setFont(new java.awt.Font("Tahoma", 1, 12));
        print.setText("Print e-ticket");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jMenu2.add(print);

        CheckPNR.setFont(new java.awt.Font("Tahoma", 1, 12));
        CheckPNR.setText("Check PNR status");
        CheckPNR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckPNRActionPerformed(evt);
            }
        });
        jMenu2.add(CheckPNR);

        passengerList.setFont(new java.awt.Font("Tahoma", 1, 12));
        passengerList.setText("Check Passenger list");
        passengerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerListActionPerformed(evt);
            }
        });
        jMenu2.add(passengerList);

        jMenuBar1.add(jMenu2);

        Profile.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Profile.setText("My Profile");
        Profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileActionPerformed(evt);
            }
        });

        profile.setText("Edit Profile");
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        Profile.add(profile);

        jMenuBar1.add(Profile);

        jMenu4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu4.setText("General");

        trainSchedule.setFont(new java.awt.Font("Tahoma", 1, 12));
        trainSchedule.setText("Check Train schedule");
        trainSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainScheduleActionPerformed(evt);
            }
        });
        jMenu4.add(trainSchedule);

        jMenuBar1.add(jMenu4);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        exitApp.setText("Exit the application");
        exitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAppActionPerformed(evt);
            }
        });
        exit.add(exitApp);

        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void travelPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travelPlanActionPerformed
new ticketBooking().setVisible(true);
    }//GEN-LAST:event_travelPlanActionPerformed

    private void ProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileActionPerformed
    }//GEN-LAST:event_ProfileActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
 new CancelBooking().setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void trainScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainScheduleActionPerformed
new trainSchedule().setVisible(true);  
    }//GEN-LAST:event_trainScheduleActionPerformed

    private void CheckPNRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckPNRActionPerformed
new CheckPNR().setVisible(true);
    }//GEN-LAST:event_CheckPNRActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
my_profile.cnameTF.setText(accountLog.name);
my_profile.cageTF.setText(""+accountLog.age);
my_profile.mobTF.setText(""+accountLog.mob);
my_profile.gmailTF.setText(accountLog.gmail);
my_profile.sexTF.setText(accountLog.sex);
new my_profile().setVisible(true);
}//GEN-LAST:event_profileActionPerformed

    private void exitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAppActionPerformed
System.exit(0);
    }//GEN-LAST:event_exitAppActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
PrintTicket ticket=new PrintTicket();
PrintTicket.journeyDate.setText(JourneyDetail.journey);
PrintTicket.train_no.setText(""+JourneyDetail.tno);
PrintTicket.to.setText(JourneyDetail.to);
PrintTicket.pnrTF.setText(""+JourneyDetail.pnr);
PrintTicket.tname.setText(JourneyDetail.tname);
PrintTicket.pname.setText(JourneyDetail.pname);
PrintTicket.from.setText(JourneyDetail.from);
PrintTicket.sexTF.setText(JourneyDetail.psex);
PrintTicket.ageTF.setText(""+JourneyDetail.page);
PrintTicket.snoTF.setText(""+JourneyDetail.sno);
PrintTicket.classType.setText(JourneyDetail.trainClass);
PrintTicket.mobile_no.setText(""+JourneyDetail.mobno);
PrintTicket.amountTF.setText("Rs."+BookTrain.totalFare);
PrintTicket.timeTF.setText(""+BookTrain.deptTime);
ticket.setVisible(true);
}//GEN-LAST:event_printActionPerformed

    private void passengerListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerListActionPerformed
new passengerList().setVisible(true);
    }//GEN-LAST:event_passengerListActionPerformed

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked
}//GEN-LAST:event_profileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CheckPNR;
    public javax.swing.JMenu Profile;
    private javax.swing.JMenuItem cancel;
    private javax.swing.JMenu exit;
    private javax.swing.JMenuItem exitApp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    public static javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem passengerList;
    public static javax.swing.JMenuItem print;
    public static javax.swing.JMenuItem profile;
    private javax.swing.JMenu services;
    private javax.swing.JMenuItem trainSchedule;
    private javax.swing.JMenuItem travelPlan;
    // End of variables declaration//GEN-END:variables
}
